### PR TITLE
Add cellular automata demos

### PR DESCRIPTION
**Pull request by cogwoz**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.
    - [ ] You updated the docs or changelog.

Related issue (if applicable): #4 

There are some changes to the initial issue which I'll highlight here.

**What kind of change does this PR introduce?**
Three new cellular automata demos.

## 01.GameOfLife
image

* Shows the classic rules from [Conway's Game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life).
* Tiles are set as alive or dead by left-clicking. This allows the user to see how different pattern change with every step.
* This basic implementation is the scaffolding to generating dungeons; it shows how we use a map which changes after each step using a set of rules.

## 02.BasicDungeon
image

* Building on the last project, we alter the rules to generate organic looking caverns.
* We have settings that we can change:
  * **Wall Chance**: How likely a cell is designated as a wall during step 0. A higher chance leads to smaller, more spread out caverns.
  * **Wall Conversion**: Each step, a floor cell turns into a wall if it has less than this number of floor neighbors.
  * **Floor Conversion**: Each step, a wall cell turns into a floor if it has greater than this number of floor neighbors.
  * **Step Count**: How many steps run before the generation completes.
  * **Step Speed**: The time between steps. Used to visually show the change between different steps.

## 03.AdvancedDungeon
image893

* Here we add features to create a simple, playable stage:
  * Autotiles with floor tile variances to make the caverns look more appealing **_(Note: the assets are placeholder.)_**
  * A player that moves with the arrow keys and can "dig" through adjacent wall tiles to each other caverns using SPACE.
  * An exit which will generate a new dungeon upon collision.
  * Treasure which spawns in corners. Treasure is picked up when the player collides with it.
* There are three more settings to change the feel of the dungeon:
  * **Switch Camera Button**: Toggles between the overhead camera and the player camera.
  * **Min Exit Distance**: The minimum distance in cells the exit has to be from the player.
  * **Min Cavern Size**: Caverns which have less cells than this value are filled in with wall tiles.
  * **Maximum Treasure**: The maximum number treasure scenes that spawn.

**Does this PR introduce a breaking change?**
Nope.

### CODE REVIEW

**Comment by NathanLovato** [comment]
May I go ahead and make code style tweaks? It's looking good at a glance, I'd just compress some functions vertically, adding a variable here and there to clarify a long conditions, renaming a handful of files, things like those.

**Comment by cogwoz** [comment]
Absolutely, no problem.

**Comment by cogwoz** [comment]
I've updated the PR with more information and context.

**Comment by NathanLovato** [comment]
Great, thanks for your work!

**Pull request merged**
